# Generated by Django 2.2.16 on 2025-01-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(verbose_name='Текст сообщения.')),
                ('message_date_time', models.TextField(verbose_name='Время и дата сообщения.')),
                ('message_type', models.TextField(verbose_name='Тип сообщения: бот или пользователь.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='userdata',
            index=models.Index(fields=['created'], name='users_userd_created_2051ff_idx'),
        ),
    ]
