# Generated by Django 2.2.16 on 2025-02-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер чата пользователя.'),
        ),
    ]
