# Generated by Django 2.2.16 on 2025-01-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('yoga', models.TextField(verbose_name='Наименование занятия.')),
                ('start_time', models.TimeField(verbose_name='Время начала занятия.')),
                ('week_day', models.TextField(choices=[('понедельник', 'понедельник'), ('вторник', 'вторник'), ('среда', 'среда'), ('четверг', 'четверг'), ('пятница', 'пятница'), ('суббота', 'суббота'), ('воскресенье', 'воскресенье')], verbose_name='День недели заняти.')),
                ('teacher', models.TextField(null=True, verbose_name='Фамилия преподавателя.')),
                ('sort_days', models.IntegerField(default=0, verbose_name='Для сортировки дней недели, понедельник = 0.')),
            ],
            options={
                'ordering': ['sort_days', 'start_time'],
            },
        ),
    ]
