# Generated by Django 2.2.16 on 2025-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cost',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость занятия.'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cost_first',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость пробного занятия.'),
        ),
    ]
