# Generated by Django 2.2.16 on 2025-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250202_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.TextField(blank=True, null=True, verbose_name='Длительность занятия.'),
        ),
    ]
